### ISSUE TITLE
No Xcode or Visual Studio projects as stated in ReadMe file

### ISSUE THREAD

**Issue by nesdnuma** [Cycling74/cv.jit#16]
Hello,

The ReadMe states that: 'You will find Visual Studio and Xcode projects in the "source/projects/Windows" and "source/projects/OSX" folders, respectively.'

However I can't see these subfolders. So how does one build the objects?

**Comment by tap** [comment]
Thanks for the report. You are correct and it looks like the ReadMe is out of date.

The projects are generated by CMake. So, for example, to generate the Xcode project on the Mac (assuming you have CMake installed) you can do the following in the Terminal:

* cd into the cv.jit folder
* `mkdir build`
* ` cd build`
* ` cmake -G Xcode ..`

Now if you look in the "build" folder you will find an Xcode project.

**Comment by lineacurva** [comment]
is this also buildable for Windows? I try to build and I'm missing files. If not buildable, where could I find the windows version?

**Comment by nesdnuma** [comment]
Thanks!
