### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by micron-visual** [Cycling74/cv.jit#18]
Hi Tap,
I "cd" into cv.jit folder, created the "build" folder and created the visual studio projects with cmake -G "Visual Studio 16 2019" -A x64 ..

now I opened the cv.jit.features project and trying to compile I get these errors.
Do I missing somthing?
Thanks
Rajan

unresolved external symbol cvInitMatHeader referenced in function "void __cdecl cvJitter2CvMat(void *,struct CvMat *)" (?cvJitter2CvMat@@YAXPEAXPEAUCvMat@@@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	

unresolved external symbol cvCreateMat referenced in function "struct _cv_jit_features * __cdecl cv_jit_features_new(void)" (?cv_jit_features_new@@YAPEAU_cv_jit_features@@XZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	

unresolved external symbol cvReleaseMat referenced in function "void __cdecl cv_jit_features_free(struct _cv_jit_features *)" (?cv_jit_features_free@@YAXPEAU_cv_jit_features@@@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	

unresolved external symbol cvFindCornerSubPix referenced in function "__int64 __cdecl cv_jit_features_matrix_calc(struct _cv_jit_features *,void *,void *)" (?cv_jit_features_matrix_calc@@YA_JPEAU_cv_jit_features@@PEAX1@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	

unresolved external symbol cvGoodFeaturesToTrack referenced in function "__int64 __cdecl cv_jit_features_matrix_calc(struct _cv_jit_features *,void *,void *)" (?cv_jit_features_matrix_calc@@YA_JPEAU_cv_jit_features@@PEAX1@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	

unresolved external symbol gensym referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol object_error referenced in function "void __cdecl cvJitter2CvMat(void *,struct CvMat *)" (?cvJitter2CvMat@@YAXPEAXPEAUCvMat@@@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol object_getmethod referenced in function "void * __cdecl c74::max::object_method(struct c74::max::t_object *,struct c74::max::t_symbol *,void *)" (?object_method@max@c74@@YAPEAXPEAUt_object@12@PEAUt_symbol@12@PEAX@Z)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_class_new referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_class_register referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_class_addmethod referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_class_addattr referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_class_addadornment referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_mop_single_type referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_mop_single_planecount referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_mop_output_nolink referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_attr_addfilterset_clip referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_object_alloc referenced in function "struct _cv_jit_features * __cdecl cv_jit_features_new(void)" (?cv_jit_features_new@@YAPEAU_cv_jit_features@@XZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_object_new_imp referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_object_method_imp referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_attr_setlong referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1	
Error	LNK2019	unresolved external symbol jit_attr_setsym referenced in function "__int64 __cdecl cv_jit_features_init(void)" (?cv_jit_features_init@@YA_JXZ)	cv.jit.features	C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build\source\projects\cv.jit.features\cv.jit.features.obj	1

**Comment by tap** [comment]
Hi,

I haven't tested this, but I think you want your cmake invocation to be 

```cmake -G "Visual Studio 16 2019 Win64" ..```

**Comment by micron-visual** [comment]
Thanks for your reply,
I tested your string but I get:

C:\Users\rajan\Documents\Max 8\Packages\cv.jit-master\build>cmake -G "Visual Studio 16 2019 Win64" ..
CMake Error: Could not create named generator Visual Studio 16 2019 Win64

Generators
* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Comment by jmpelletier** [comment]
Hi Tim,

So sorry, the code on Github wasn't up to date. I've updated the build
instructions and pushed the latest code. I tried on macOS and Windows and
had no issues. I don't have VS 2019 installed here, so I used VS 2017.

Cheers,

Jean-Marc

**Comment by tap** [comment]
Thanks, Jean-Marc!

The answer turns out to be `cmake -G "Visual Studio 16 2019" ..` which produces x64 projects without any additional options needing to be specified.

Cheers,
Tim
