### ISSUE TITLE
Max crash when you click on  cv.jit.learn write message 

### ISSUE THREAD

**Issue by Marousah** [Cycling74/cv.jit#22]
It happens for me in win10 and macOs 12.1 (intel) - Max 8.5.2

**Comment by carmelofascella** [comment]
I have the same problem. Has anyone found a solution?

**Comment by jmpelletier** [comment]
Hi, I created a pull request that fixes the problem. Sorry for the inconvenience.

**Comment by robtherich** [comment]
This fix is now live in the Package Manager, cv.jit version 2.0.2. Thanks much for reporting (and to jmp for fixing)!
